### ISSUE TITLE
Undefined index: cf7slide_security makes ajax loader spin forever

### ISSUE THREAD

**Issue by S4Mi** [aurovrata/cf7-multislide#1]
`$security = $posted_data['cf7slide_security'];` on line 263 of `Cf7_Multislide_Admin` class creates a php notice:
`PHP Notice:  Undefined index: cf7slide_security in wp-content/plugins/cf7-multislide/admin/class-cf7-multislide-admin.php on line 263`
Which further makes some troubles and conflict with cf7 for non multislide forms.
I would've created a PR if it wasn't just a one liner fix.

Thanks

**Comment by aurovrata** [comment]
sure, thanks for the heads up.  There is a new version that is being released shortly in which I will fix this

**Comment by aurovrata** [comment]
just released a bug fix for this, v1.1.1.  It was actually a one-liner :)
